# Generated by Django 3.0.3 on 2020-02-11 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import django_s3_storage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gronner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extract', models.TextField(blank=True, default='', null=True)),
                ('dedication', models.CharField(default='Gronner', max_length=40)),
                ('points', models.IntegerField(default=0)),
                ('image', models.ImageField(default='https://gronno-media.s3.amazonaws.com/default.jpg', storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='gronno-media'), upload_to='')),
                ('birth', models.DateField()),
                ('country', django_countries.fields.CountryField(blank=True, default='Argentina', max_length=2, null=True)),
                ('facebook', models.CharField(blank=True, default='', max_length=50)),
                ('instagram', models.CharField(blank=True, default='', max_length=50)),
                ('linkedin', models.CharField(blank=True, default='', max_length=50)),
                ('twitter', models.CharField(blank=True, default='', max_length=50)),
                ('shows_email', models.BooleanField(default=False)),
                ('categories_followed', models.ManyToManyField(to='project.Category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
