# Generated by Django 3.0.3 on 2020-09-03 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import django_s3_storage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.CharField(default='/', max_length=100)),
                ('color', models.CharField(default='#000', max_length=15)),
                ('seen', models.BooleanField(default=False)),
                ('other_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gronner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extract', models.TextField(blank=True, default='', null=True)),
                ('dedication', models.CharField(default='Gronner', max_length=40)),
                ('points', models.IntegerField(default=0)),
                ('image', models.ImageField(default='default.jpg', storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name=None), upload_to='')),
                ('birth', models.DateField()),
                ('country', django_countries.fields.CountryField(blank=True, default='Argentina', max_length=2, null=True)),
                ('facebook', models.CharField(blank=True, default='', max_length=50)),
                ('instagram', models.CharField(blank=True, default='', max_length=50)),
                ('linkedin', models.CharField(blank=True, default='', max_length=50)),
                ('twitter', models.CharField(blank=True, default='', max_length=50)),
                ('shows_email', models.BooleanField(default=False)),
                ('categories_followed', models.ManyToManyField(blank=True, to='project.Category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
