# Generated by Django 3.0.2 on 2020-01-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gronner',
        ),
    ]
