# Generated by Django 3.0.2 on 2020-01-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_gronner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Network',
            new_name='Social_media',
        ),
    ]
