# Generated by Django 3.0.2 on 2020-01-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200127_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='gronner',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
