# Generated by Django 3.0.2 on 2020-01-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_gronner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gronner',
            name='extract',
            field=models.TextField(default=''),
        ),
    ]
