# Generated by Django 3.0.2 on 2020-01-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200127_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gronner',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
