# Generated by Django 3.0.3 on 2020-02-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200218_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
