# Generated by Django 3.0.2 on 2020-01-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200127_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gronner',
            name='extract',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
