# Generated by Django 3.0.3 on 2020-02-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200218_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='color',
            field=models.CharField(default='#000', max_length=15),
        ),
    ]
