# Generated by Django 3.0.2 on 2020-01-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200127_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gronner',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
