# Generated by Django 3.0.2 on 2020-01-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200125_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='gronner',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
