# Generated by Django 3.0.2 on 2020-01-29 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200127_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dedication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='gronner',
            name='dedication',
            field=models.ForeignKey(default='Gronner', on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Dedication'),
        ),
    ]
