# Generated by Django 3.0.2 on 2020-01-30 14:36

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200129_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='gronner',
            name='country',
            field=django_countries.fields.CountryField(default='Selecciona un país', max_length=2),
        ),
    ]
