# Generated by Django 3.0.2 on 2020-01-30 14:37

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_gronner_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gronner',
            name='country',
            field=django_countries.fields.CountryField(default='Argentina', max_length=2),
        ),
    ]
