# Generated by Django 3.0.2 on 2020-01-31 00:12

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gronner',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='0', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='gronner',
            name='dedication',
            field=models.ForeignKey(blank=True, default='Gronner', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Dedication'),
        ),
    ]
