# Generated by Django 3.0.2 on 2020-01-31 10:39

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200131_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='gronner',
            name='email',
            field=models.EmailField(default='example@address.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='gronner',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='Argentina', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='gronner',
            name='dedication',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Dedication'),
        ),
    ]
