# Generated by Django 3.0.2 on 2020-01-31 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200131_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gronner',
            name='email',
        ),
    ]
