# Generated by Django 3.0.2 on 2020-01-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_gronner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='gronner',
            name='facebook',
            field=models.URLField(default='facebook.com/your_user'),
        ),
        migrations.AddField(
            model_name='gronner',
            name='instagram',
            field=models.URLField(default='instagram.com/your_user'),
        ),
        migrations.AddField(
            model_name='gronner',
            name='linkedin',
            field=models.URLField(default='linkedin.com/in/your_user'),
        ),
        migrations.AddField(
            model_name='gronner',
            name='twitter',
            field=models.URLField(default='facebook.com/your_user'),
        ),
    ]
