# Generated by Django 3.0.2 on 2020-01-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200131_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gronner',
            name='facebook',
            field=models.URLField(default='facebook.com/tu_usuario', null=True),
        ),
        migrations.AlterField(
            model_name='gronner',
            name='instagram',
            field=models.URLField(default='instagram.com/tu_usuario', null=True),
        ),
        migrations.AlterField(
            model_name='gronner',
            name='linkedin',
            field=models.URLField(default='linkedin.com/in/tu_usuario', null=True),
        ),
        migrations.AlterField(
            model_name='gronner',
            name='twitter',
            field=models.URLField(default='facebook.com/tu_usuario', null=True),
        ),
    ]
