# Generated by Django 3.0.2 on 2020-01-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200131_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gronner',
            name='facebook',
            field=models.URLField(blank=True, default='facebook.com/tu_usuario'),
        ),
        migrations.AlterField(
            model_name='gronner',
            name='instagram',
            field=models.URLField(blank=True, default='instagram.com/tu_usuario'),
        ),
        migrations.AlterField(
            model_name='gronner',
            name='linkedin',
            field=models.URLField(blank=True, default='linkedin.com/in/tu_usuario'),
        ),
        migrations.AlterField(
            model_name='gronner',
            name='twitter',
            field=models.URLField(blank=True, default='facebook.com/tu_usuario'),
        ),
    ]
