# Generated by Django 3.0.2 on 2020-01-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200131_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gronner',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='gronner',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='gronner',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='gronner',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
