# Generated by Django 3.0.2 on 2020-01-31 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200131_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_media',
            name='network',
        ),
        migrations.RemoveField(
            model_name='social_media',
            name='user',
        ),
        migrations.DeleteModel(
            name='Network',
        ),
        migrations.DeleteModel(
            name='Social_media',
        ),
    ]
