# Generated by Django 3.0.2 on 2020-02-01 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200131_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='gronner',
            name='birth',
            field=models.DateField(default=datetime.datetime(2020, 2, 1, 13, 24, 59, 779645)),
        ),
    ]
