# Generated by Django 3.0.2 on 2020-02-01 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_gronner_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gronner',
            name='birth',
            field=models.DateField(default=datetime.datetime(2020, 2, 1, 13, 26, 4, 299571, tzinfo=utc)),
        ),
    ]
