# Generated by Django 3.0.2 on 2020-02-02 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200202_1437'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0024_auto_20200201_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='gronner',
            name='categories_followed',
            field=models.ManyToManyField(to='project.Category'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
