# Generated by Django 3.0.2 on 2020-02-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20200202_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='gronner',
            name='shows_email',
            field=models.BooleanField(default=True),
        ),
    ]
