# Generated by Django 3.0.2 on 2020-02-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_gronner_shows_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='gronner',
            name='first_categories',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='gronner',
            name='shows_email',
            field=models.BooleanField(default=False),
        ),
    ]
