# Generated by Django 3.0.3 on 2020-02-11 18:04

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image1',
            field=models.ImageField(storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name=None), upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name=None), upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=models.ImageField(storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name=None), upload_to=''),
        ),
    ]
