# Generated by Django 3.0.2 on 2020-01-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short',
            field=models.CharField(default='Put here diminutive category name', max_length=10),
        ),
    ]
