# Generated by Django 3.0.2 on 2020-01-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_category_short'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='short',
            new_name='diminutive',
        ),
    ]
