# Generated by Django 3.0.2 on 2020-01-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200129_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
