# Generated by Django 3.0.2 on 2020-01-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200123_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='diminutive',
            field=models.CharField(max_length=255),
        ),
    ]
