# Generated by Django 3.0.2 on 2020-01-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200123_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='diminutive',
        ),
    ]
