# Generated by Django 3.0.2 on 2020-01-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_category_diminutive'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='diminutive',
            field=models.CharField(default='Put here a diminutive name', max_length=10),
        ),
    ]
