# Generated by Django 3.0.2 on 2020-02-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200201_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_pics'),
        ),
    ]
