# Generated by Django 3.0.2 on 2020-01-26 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20200125_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medal',
            old_name='name',
            new_name='medal_type',
        ),
        migrations.RemoveField(
            model_name='medal',
            name='project',
        ),
        migrations.AddField(
            model_name='medal',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Medal')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
